- name: Creating worker launch template
  vars:
    joinWorkerCommand: "{{lookup('file', '/tmp/kubeadm-join-worker.txt')}}"
    #quem criou o kubeadm-join-worker foi uma role
  template:
    src: worker-user-data-v2.j2
    dest: /tmp/worker-launch-template.sh

- name: Update worker launch template
  vars:
    terraform_outputs: "{{lookup('file', '{{terraform_path}}/server/outputs.json')}}"
    worker_launch_template_id: "{{terraform_outputs.worker_launch_template_id.value}}"
  environment:
    AWS_PROFILE: "{{aws_profile}}"
  ec2_launch_template:
    template_id: "{{worker_launch_template_id}}"
    user_data: "{{lookup('file', '/tmp/worker-user-data-v2.sh') | b64encode}}"
