#para fazer o ping nas instancias do playbook
---
- name: Setting up cluster
  hosts: aws_ec2 #para instalar em todos
  become: true #become significa que ira fazer um sudo na minha maquina, entao, ele
  #precisa de um password que e fornecido com o comando:
  #andible-playbook -i production.aws_ec2.yml site.yml --ask-become-pass
  #sendo solicitado a senha em tempo de execucao
  roles:
    - hostnames
    - dependency-packages
    - kube-packages
    - container-runtime
    #comando ansbile: ansible-playbook -i production site.yml
    # - kubeadm-init-first-master
    #comando ansbile para rodar a linha acima:
    #ansible-playbook -i production site.yml --ask-become-pass
    #isso e uma integracao do terraform com o ansible para pegar a informacao
    #do DNS do network load balancer

---
- name: Init Cluster
  hosts: control_planes[0]
  become: true
  environment:
    KUBECONFIG: "{{kube_config}}"
  roles:
    - init-cluster
    - set-provider-id
    - container-network

---
- name: Join control planes
  #todos control_planes menos no primeiro:
  hosts: control_planes:!control_planes[0]
  become: true
  environment:
    KUBECONFIG: "{{kube_config}}"
  roles:
    - join-control-planes
    - set-provider-id

- name: Join workers
  hosts: workers
  become: true
  environment:
    KUBECONFIG: "{{kube_config_worker}}"
  roles:
    - join-workers
    - set-provider-id

- name: Update launch template
  hosts: localhost
  gather_facts: false
  roles:
    - update-launch-template

---
- name: Setting up cluster auto scaler
  hosts: control_planes[0]
  become: true
  environment:
    KUBECONFIG: "{{kube_config}}"
  roles:
    - cloud-controller
    - node-termination
    - cluster-autoscaler
    - argocd
    - metrics-server
    - load-balancer-controller
    - container-storage
