#para fazer o ping nas instancias do playbook
---
- name: Creating Kube Adm Kubernetes cluster
  hosts: aws_ec2 #para instalar em todos
  become: true
  roles:
    - dependency-packages
    - kube-packages
    - container-runtime
    #comando ansbile: ansible-playbook -i production site.yml
    # - kubeadm-init-first-master
    #comando ansbile para rodar a linha acima:
    #ansible-playbook -i production site.yml --ask-become-pass
    #isso e uma integracao do terraform com o ansible para pegar a informacao
    #do DNS do network load balancer

---
- name: KubeAdm Init First Control Plane
  hosts: control_planes[0]
  become: true
  environment:
    KUBECONFIG: "{{kube_config}}"
  roles:
    - kubeadm-init-first-master
    - container-network
