//para fazer o ping nas instancias do playbook

---
- name: Ping control planes
  hosts: control_planes
  become: true
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: nsse-ansible-ssm
  tasks:
    - name: Ping control control_planes
      ansible.builtin.ping:


//comando ansbile: ansible-playbook -i production site.yml