---
- name: Installing dependency packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - software-properties-common #dependencia do CRI-O
      #(pacotes do kubernetes)
    update_cache: true #e como o uso do sudo apt-get update
