---
- name: Generate join command
  shell: kubeadm token create --print-job-command --ttl 0
  register: join_command_output

- name: Generate Certificate Key
  shell: kubeadm init phase upload-certs --upload-certs | tail -n 1
  register: certificate_key_output

- name: Write join command to file
  copy:
    content: "{{join_command_output.stdout }}--control-plane --certificate-key {{certificate_key_output.stdout}}"
    dest: /tmp/kubeadm-join-control-plane.txt
  delegate_to: localhost
