#a informacao do hostname para atualizacao do DNS da instancia e obtida atraves
#de metadados com o comando curl
---
- name: Updating hostnames
  shell: hostnamectl set-hostname $(curl http://169.254.169.254/latest/meta-data/hostname)
