#url da documentacao: https://github.com/aws/aws-node-termination-handler

- name: Authenticate public ECR
  shell: |
    aws ecr-public get-login-password \
    --region {{aws_region}} | helm registry login \
    --username AWS \
    --password-stdin public.ecr.aws

- name: Instaling AWS Node Termination Handler
  vars:
    terraform_outputs: "{{lookup('file', '{{terraform_path}}/server/outputs.json')}}"
    node_termination_queue_url: "{{terraform_outputs.node_termination_queue_url.value}}"
    #rollout restart coredns devido a erros durante a execucao
  shell: |
    kubect rollout restart deploy/coredns -n kube-system
    helm upgrade --install aws-node-termination-handler \
    --namespace kube-system \
    --set enableSpotInterruptionDraining="true" \
    --set enableRebalanceMonitoring="true" \
    --set enableScheduledEventDraining="false" \
    oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler
